version: '2.1'
services:
    mysql:
        build: ./database
        environment:
            - MYSQL_DATABASE="fec"
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        healthcheck:
            test: "exit 0"
        ports:
            - "3306:3306"

    myawesomeapp:
        build: .
        depends_on:
            mysql:
                condition: service_healthy
        ports:
            - "3008:3008"
        # # entrypoint:
        # #     - /usr/local/bin/docker-entrypoint.sh
        # links:
        #     - mysql