version: '2.1'
services:
    mysql:
        build: ./database
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        healthcheck:
            test: "exit 0"

    myawesomeapp:
        build: .
        depends_on:
            mysql:
                condition: service_healthy
        ports:
            - "3008:3008"
        links:
            - mysql